
//import { Inter } from "next/font/google";
import "./globals.css";

import { CarouselProvider } from "./context/carouselContext";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CDSS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className="">
        <CarouselProvider>

      <div className="container">
        <div className="wrapper">
          
        {children}
        </div>
      </div>
        </CarouselProvider>
        </body>
    </html>
  );
}
